### ISSUE TITLE
Failing container

### ISSUE THREAD

**Issue by danionescu0** [danionescu0/docker-flask-mongodb-example#143]
ocker-flask-mongodb-example-web-baesian-1             | Traceback (most recent call last):
docker-flask-mongodb-example-web-baesian-1             |   File "/root/flask-mongodb-example/python/baesian/baesian.py", line 3, in <module>
docker-flask-mongodb-example-web-baesian-1             |     from flask import Flask, request, Response
docker-flask-mongodb-example-web-baesian-1             |   File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 7, in <module>
docker-flask-mongodb-example-web-baesian-1             |     from .app import Flask as Flask
docker-flask-mongodb-example-web-baesian-1             |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 28, in <module>
docker-flask-mongodb-example-web-baesian-1             |     from . import cli
docker-flask-mongodb-example-web-baesian-1             |   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 18, in <module>
docker-flask-mongodb-example-web-baesian-1             |     from .helpers import get_debug_flag
docker-flask-mongodb-example-web-baesian-1             |   File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 16, in <module>
docker-flask-mongodb-example-web-baesian-1             |     from werkzeug.urls import url_quote
docker-flask-mongodb-example-web-baesian-1             | ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.10/site-packages/werkzeug/urls.py)

**Comment by danionescu0** [comment]
Fixed!
